[package]
name = "bmm-lib"
version = "0.2.2"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
bincode = { version = "2.0.1", features = ["serde"] }
bytes = "1.10.1"
chrono = "0.4.40"
dirs = "6.0.0"
discord-rich-presence = "0.2.5"
env_logger = "0.11.7"
flate2 = { version = "1.1.0", features = ["zlib"] }
infer = "0.16.0"
lazy_static = "1.5.0"
libc = "0.2.171"
libflate = "2.1.0"
log = "0.4.26"
regex = "1.11.1"
reqwest = { version = "0.12.15", features = ["json"] }
rusqlite = { version = "0.34.0", features = ["bundled"] }
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_json = "1.0.140"
serde_repr = "0.1.20"
tar = "0.4.44"
tauri = "2.3.1"
tempfile = "3.19.0"
tokio = { version = "1.44.1", features = ["full"] }
zip = "2.4.1"

[dev-dependencies]
tempfile = "3.19.0"
scopeguard = "1.2.0"
mockito = "1.7.0"
tokio = { version = "1.44.1", features = ["full", "test-util"] }
rstest = "0.25.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.52.0"
sysinfo = "0.33.1"

[target.'cfg(unix)'.dependencies]
libproc = "0.14.10"
home = "0.5.11"
# libloading = "0.8.6"

[build-dependencies]
dirs = "6.0.0"
